site_name: AI Agent Concepts

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - 👋 Introduction: index.md
  - 👨🏼‍💻 Basics of Prompt Writing: prompt_writing.md
  - 🎓 AI Agent 101: ai_agent_101.md
  - 🛠️ Agent Harness: ai_agent_harness.md
  - 📚 Context Engineering: context_engineering.md
  - 💾 Memory Management: memory_management.md
